### Create order from Cart
###  projects/poc-gcp-439306/subscriptions/notifications-sub22 
POST http://localhost:3001/api/payment/order-handler
Content-Type: application/json

{
  "cart" : {
    "id" : "7afbadd5-bc82-488e-bd27-edf4c9daf98c",
    "typeId" : "cart"
  },
  "version" : 1,
  "orderState":"Complete",
  "paymentState":"Paid",
  "shipmentState":"Shipped"
}

### test mock server
GET http://localhost:3100/v1/cw_au/stores/stock/search


### read file
GET http://localhost:3002/api/user/read/file


### test pubsub
GET http://localhost:3002/api/user/test1


### forward
POST http://localhost:3001/api/payment/handler1?v=222
Content-Type: application/json

{
  "cart" : {
    "id" : "7afbadd5-bc82-488e-bd27-edf4c9daf98c",
    "typeId" : "cart"
  },
  "version" : 1,
  "orderState":"Complete",
  "paymentState":"Paid",
  "shipmentState":"Shipped"
}